from django.urls import path

from .superadmin_views import (
    dashboard,
    organization_detail,
    organization_list,
    organization_status,
    organization_create,
    organization_update,
    organization_lifecycle,
    user_detail,
    user_list,
    user_password_reset,
    user_status,
    user_create,
    user_update,
    user_transfer,
    project_detail,
    project_pivot_reviewer_assign,
    project_concierge_update,
    project_dispute_open,
    project_dispute_observe,
    project_dispute_resolve,
    pivot_onboarding_create,
    pivot_project_invite,
    onboarding_conflict_resolve,
    project_intervene,
    project_content_action,
    project_content_preview,
    project_list,
    pilot_recommendation_create,
    pilot_pricing_hypothesis_create,
    validation_document_decide,
    validation_document_preview,
    validation_queue,
    validation_withdrawal_decide,
    audit_event_detail,
    audit_event_list,
    platform_settings,
    subscription_intervene,
    subscription_list,
    subscription_plan_create,
    subscription_plan_update,
)

app_name = "superadmin"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("organisations/", organization_list, name="organization-list"),
    path("organisations/creer/", organization_create, name="organization-create"),
    path("organisations/<int:pk>/", organization_detail, name="organization-detail"),
    path("organisations/<int:pk>/modifier/", organization_update, name="organization-update"),
    path("organisations/<int:pk>/cycle-de-vie/", organization_lifecycle, name="organization-lifecycle"),
    path("organisations/<int:pk>/statut/", organization_status, name="organization-status"),
    path("utilisateurs/", user_list, name="user-list"),
    path("utilisateurs/creer/", user_create, name="user-create"),
    path("utilisateurs/<int:pk>/", user_detail, name="user-detail"),
    path("utilisateurs/<int:pk>/modifier/", user_update, name="user-update"),
    path("utilisateurs/<int:pk>/transferer/", user_transfer, name="user-transfer"),
    path("utilisateurs/<int:pk>/statut/", user_status, name="user-status"),
    path(
        "utilisateurs/<int:pk>/reinitialiser-mot-de-passe/",
        user_password_reset,
        name="user-password-reset",
    ),
    path("projets/", project_list, name="project-list"),
    path("pilote/recommandations/ajouter/", pilot_recommendation_create, name="pilot-recommendation-create"),
    path("pilote/pricing/ajouter/", pilot_pricing_hypothesis_create, name="pilot-pricing-create"),
    path("projets/onboarding-pivot/nouveau/", pivot_onboarding_create, name="pivot-onboarding-create"),
    path("projets/<uuid:pk>/", project_detail, name="project-detail"),
    path("projets/<uuid:pk>/verificateur-pivot/", project_pivot_reviewer_assign, name="project-pivot-reviewer-assign"),
    path("projets/<uuid:pk>/concierge/", project_concierge_update, name="project-concierge-update"),
    path("projets/<uuid:pk>/contestations/ouvrir/", project_dispute_open, name="project-dispute-open"),
    path("projets/<uuid:pk>/contestations/<uuid:dispute_pk>/observer/", project_dispute_observe, name="project-dispute-observe"),
    path("projets/<uuid:pk>/contestations/<uuid:dispute_pk>/resoudre/", project_dispute_resolve, name="project-dispute-resolve"),
    path("projets/<uuid:pk>/inviter/", pivot_project_invite, name="pivot-project-invite"),
    path("projets/<uuid:pk>/conflits/<int:conflict_pk>/resoudre/", onboarding_conflict_resolve, name="onboarding-conflict-resolve"),
    path("projets/<uuid:pk>/intervenir/", project_intervene, name="project-intervene"),
    path(
        "projets/<uuid:pk>/contenus/<str:target_type>/<uuid:target_pk>/action/",
        project_content_action,
        name="project-content-action",
    ),
    path(
        "projets/<uuid:pk>/contenus/<str:target_type>/<uuid:target_pk>/apercu/",
        project_content_preview,
        name="project-content-preview",
    ),
    path("validations/", validation_queue, name="validation-queue"),
    path("validations/document/<uuid:pk>/decider/", validation_document_decide, name="validation-document-decide"),
    path("validations/document/<uuid:pk>/apercu/", validation_document_preview, name="validation-document-preview"),
    path("validations/retrait/<uuid:pk>/decider/", validation_withdrawal_decide, name="validation-withdrawal-decide"),
    path("audit/", audit_event_list, name="audit-list"),
    path("audit/<int:pk>/", audit_event_detail, name="audit-detail"),
    path("parametres/", platform_settings, name="settings"),
    path("abonnements/", subscription_list, name="subscription-list"),
    path("abonnements/forfaits/creer/", subscription_plan_create, name="subscription-plan-create"),
    path("abonnements/forfaits/<uuid:pk>/modifier/", subscription_plan_update, name="subscription-plan-update"),
    path("abonnements/<uuid:pk>/intervenir/", subscription_intervene, name="subscription-intervene"),
]
