# Generated by Django 5.1.5 on 2026-08-20 12:45

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.projects.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, verbose_name="description"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="localisation")),
                ("project_date", models.DateField(verbose_name="date du projet")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("ongoing", "En cours"),
                            ("complete", "Terminé"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="statut",
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="budget",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.projects.models.project_cover_path,
                        validators=[apps.projects.models.validate_project_image_size],
                        verbose_name="image de couverture",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ingénieur responsable",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="organizations.organization",
                        verbose_name="organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "projet",
                "verbose_name_plural": "projets",
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "status"], name="projects_pr_organiz_8941e0_idx"
                    ),
                    models.Index(
                        fields=["organization", "-updated_at"],
                        name="projects_pr_organiz_7ff008_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("budget_amount__gte", 0)),
                        name="project_budget_non_negative",
                    )
                ],
            },
        ),
    ]
