# Generated by Django 5.1.5 on 2026-08-20 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "project_role",
                    models.CharField(
                        choices=[("client", "Client"), ("site_manager", "Responsable de chantier")],
                        max_length=20,
                        verbose_name="rôle projet",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="affecté le")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="organizations.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                        verbose_name="projet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "affectation projet",
                "verbose_name_plural": "affectations projet",
                "ordering": ("user__username",),
                "indexes": [
                    models.Index(
                        fields=["organization", "user"], name="projects_pr_organiz_843c85_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "user"), name="unique_project_membership"
                    )
                ],
            },
        ),
    ]
