# Generated by Django 5.1.5 on 2026-08-20 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projectmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("ongoing", "En cours"),
                            ("complete", "Terminé"),
                        ],
                        max_length=16,
                        verbose_name="ancien statut",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("ongoing", "En cours"),
                            ("complete", "Terminé"),
                        ],
                        max_length=16,
                        verbose_name="nouveau statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="modifié le")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acteur",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="projects.project",
                        verbose_name="projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique de statut projet",
                "verbose_name_plural": "historiques de statut projet",
                "ordering": ("-created_at",),
            },
        ),
    ]
