# Generated by Django 5.1.5 on 2026-09-04 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_confirmed_ownerships(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Membership = apps.get_model("projects", "ProjectMembership")
    Ownership = apps.get_model("projects", "ProjectOwnership")

    for project in Project.objects.all().iterator():
        owners = list(
            Membership.objects.filter(project_id=project.pk, project_role="owner").order_by("pk")
        )
        if not owners:
            continue
        primary = owners[0]
        if len(owners) > 1:
            Membership.objects.filter(pk__in=[item.pk for item in owners[1:]]).update(
                project_role="contractor"
            )
        Ownership.objects.create(
            project_id=project.pk,
            organization_id=project.organization_id,
            owner_id=primary.user_id,
            is_confirmed=True,
            confirmed_at=timezone.now(),
            confirmed_by_id=primary.user_id,
            terms_version="legacy-2026-09",
            terms_accepted=True,
        )


def remove_backfilled_ownerships(apps, schema_editor):
    apps.get_model("projects", "ProjectOwnership").objects.filter(
        terms_version="legacy-2026-09"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0004_contextual_project_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='confirmé')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmé le')),
                ('terms_version', models.CharField(blank=True, max_length=40, verbose_name='version des conditions')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='conditions acceptées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'ownership du projet',
                'verbose_name_plural': 'ownerships des projets',
            },
        ),
        migrations.CreateModel(
            name='ProjectOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='modifié le')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='projectownership',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_project_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='confirmé par'),
        ),
        migrations.AddField(
            model_name='projectownership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ownerships', to='organizations.organization', verbose_name='organisation'),
        ),
        migrations.AddField(
            model_name='projectownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_project_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AddField(
            model_name='projectownership',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='projects.project', verbose_name='projet'),
        ),
        migrations.AddField(
            model_name='projectownershiphistory',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_ownership_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectownershiphistory',
            name='new_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_project_ownerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectownershiphistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='projectownershiphistory',
            name='previous_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_project_ownerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectownershiphistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='projects.project'),
        ),
        migrations.RunPython(backfill_confirmed_ownerships, remove_backfilled_ownerships),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('project_role', 'owner')), fields=('project',), name='unique_project_owner_role'),
        ),
    ]
