# Generated by Django 5.1.5 on 2026-09-04 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0005_confirmed_project_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAuthorityMigrationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_client', 'Aucun client affecté'), ('multiple_clients', 'Plusieurs clients affectés')], max_length=32, verbose_name='motif')),
                ('status', models.CharField(choices=[('open', 'À examiner'), ('resolved', 'Résolu')], default='open', max_length=16, verbose_name='statut')),
                ('candidate_user_ids', models.JSONField(blank=True, default=list, verbose_name='clients candidats')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='détecté le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='résolu le')),
                ('resolution_note', models.CharField(blank=True, max_length=500, verbose_name='note de résolution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority_migration_reviews', to='organizations.organization', verbose_name='organisation')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='authority_migration_review', to='projects.project', verbose_name='projet')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_authority_migration_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "revue de migration d'autorité",
                'verbose_name_plural': "revues de migration d'autorité",
                'ordering': ('status', 'project__name'),
            },
        ),
    ]
