# Generated by Django 5.1.5 on 2026-09-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0006_authority_migration_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='ingénieur responsable'),
        ),
        migrations.CreateModel(
            name='ProjectOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(choices=[('client_led', 'Initié par le client'), ('contractor_led', "Initié par l'entrepreneur"), ('pivot_led', 'Initié par PIVOT')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'À compléter'), ('ready', 'Prêt à activer'), ('active', 'Activé')], default='draft', max_length=16)),
                ('financial_conditions', models.TextField(max_length=3000)),
                ('conditions_version', models.CharField(default='2026-09-v1', max_length=40)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_project_onboardings', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_project_onboardings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_onboardings', to='organizations.organization')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='projects.project')),
            ],
        ),
    ]
