# Generated by Django 5.1.5 on 2026-09-04 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_terms_versions(apps, schema_editor):
    Onboarding = apps.get_model('projects', 'ProjectOnboarding')
    Terms = apps.get_model('projects', 'ProjectTermsVersion')
    Ownership = apps.get_model('projects', 'ProjectOwnership')
    for onboarding in Onboarding.objects.select_related('project').iterator():
        ownership = Ownership.objects.filter(project_id=onboarding.project_id).first()
        Terms.objects.create(
            project_id=onboarding.project_id,
            organization_id=onboarding.organization_id,
            version=1,
            budget_amount=onboarding.project.budget_amount,
            currency='XAF',
            financial_conditions=onboarding.financial_conditions,
            authority_owner_id=ownership.owner_id if ownership else None,
            created_by_id=onboarding.initiated_by_id,
            is_current=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0007_client_led_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=0, max_digits=16)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('financial_conditions', models.TextField(max_length=3000)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_terms_authorities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_terms', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_versions', to='projects.project')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='ProjectActorConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(choices=[('owner', 'Propriétaire du chantier'), ('contractor', 'Entrepreneur'), ('site_manager', 'Responsable de chantier'), ('engineer', 'Ingénieur'), ('pivot_reviewer', 'Vérificateur PIVOT')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_confirmations', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_actor_confirmations', to=settings.AUTH_USER_MODEL)),
                ('terms_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_confirmations', to='projects.projecttermsversion')),
            ],
        ),
        migrations.RunPython(backfill_terms_versions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='projecttermsversion',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_project_terms_version'),
        ),
        migrations.AddConstraint(
            model_name='projecttermsversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('project',), name='unique_current_project_terms'),
        ),
        migrations.AddConstraint(
            model_name='projectactorconfirmation',
            constraint=models.UniqueConstraint(fields=('terms_version', 'user', 'project_role'), name='unique_actor_confirmation_per_terms'),
        ),
    ]
