# Generated by Django 5.1.5 on 2026-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_versioned_terms_and_actor_confirmations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactorconfirmation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('expired', 'Expirée')], default='pending', max_length=16),
        ),
    ]
