# Generated by Django 5.1.5 on 2026-09-04 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0009_actor_confirmation_expiration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingConflictReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('probable_duplicate', 'Doublon probable'), ('ownership_conflict', "Conflit d'ownership")], max_length=32)),
                ('status', models.CharField(choices=[('open', 'À examiner'), ('resolved', 'Résolu')], default='open', max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('candidate_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_conflict_candidates', to='projects.project')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_conflicts', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_onboarding_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', '-detected_at'),
                'constraints': [models.UniqueConstraint(fields=('project', 'candidate_project', 'reason'), name='unique_onboarding_conflict_review')],
            },
        ),
    ]
