# Generated by Django 5.1.5 on 2026-09-08 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0010_onboarding_conflict_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConciergeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_completed', models.BooleanField(default=False)),
                ('friction', models.CharField(blank=True, max_length=1000)),
                ('next_action', models.CharField(max_length=1000)),
                ('next_action_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_follow_up', to='projects.projectonboarding')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_concierge_follow_ups', to='organizations.organization')),
                ('pivot_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concierge_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_concierge_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
