# Generated by Django 5.1.5 on 2026-09-08 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0008_evidencerecord_preview_file_and_more'),
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0011_projectconciergefollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('document', 'Document'), ('expense_request', 'Demande de dépense'), ('evidence', 'Preuve'), ('inventory_anomaly', 'Anomalie de stock')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('subject', models.CharField(max_length=200)),
                ('reason', models.TextField(max_length=3000)),
                ('freezes_decision', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('resolved', 'Résolue')], default='open', max_length=12)),
                ('resolution', models.TextField(blank=True, max_length=3000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_disputes', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='projects.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_project_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_project_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectDisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='projects.projectdispute')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_links', to='collaboration.evidencerecord')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDisputeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('claimant', 'Demandeur'), ('respondent', 'Partie contradictoire'), ('pivot', 'PIVOT')], max_length=16)),
                ('body', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_dispute_observations', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='projects.projectdispute')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='projectdispute',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('project', 'target_type', 'target_id'), name='one_open_dispute_per_project_target'),
        ),
        migrations.AddConstraint(
            model_name='projectdisputeevidence',
            constraint=models.UniqueConstraint(fields=('dispute', 'evidence'), name='unique_dispute_evidence'),
        ),
    ]
