# Generated by Django 5.1.5 on 2026-08-14 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="adresse e-mail")),
                (
                    "role",
                    models.CharField(
                        choices=[("client", "Client"), ("site_manager", "Responsable de chantier")],
                        max_length=20,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(max_length=64, unique=True, verbose_name="empreinte du jeton"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.accounts.models.invitation_expiration, verbose_name="expire le"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="acceptée le"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invité par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="organizations.organization",
                        verbose_name="organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "email"], name="accounts_in_organiz_a2b374_idx"
                    )
                ],
            },
        ),
    ]
