# Generated by Django 5.1.5 on 2026-08-14 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30, verbose_name="téléphone")),
                (
                    "location",
                    models.CharField(blank=True, max_length=160, verbose_name="localisation"),
                ),
                ("bio", models.TextField(blank=True, max_length=600, verbose_name="biographie")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.accounts.models.profile_avatar_path,
                        validators=[apps.accounts.models.validate_avatar_size],
                        verbose_name="photo de profil",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil utilisateur",
                "verbose_name_plural": "profils utilisateurs",
            },
        ),
    ]
