# Generated by Django 5.1.5 on 2026-09-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invitation_canceled_at'),
        ('projects', '0006_authority_migration_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_invitations', to='projects.project', verbose_name='projet'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='project_role',
            field=models.CharField(blank=True, choices=[('contractor', 'Entrepreneur'), ('site_manager', 'Responsable de chantier'), ('engineer', 'Ingénieur')], max_length=24, verbose_name='rôle projet'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('contractor', 'Entrepreneur'), ('site_manager', 'Responsable de chantier'), ('engineer', 'Ingénieur')], max_length=20, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('engineer', 'Ingénieur'), ('client', 'Client'), ('contractor', 'Entrepreneur'), ('site_manager', 'Responsable de chantier'), ('admin', 'Administrateur')], default='client', max_length=20, verbose_name='rôle'),
        ),
    ]
