# Generated by Django 5.1.5 on 2026-09-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_client_led_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='project_role',
            field=models.CharField(blank=True, choices=[('owner', 'Propriétaire'), ('contractor', 'Entrepreneur'), ('site_manager', 'Responsable de chantier'), ('engineer', 'Ingénieur')], max_length=24, verbose_name='rôle projet'),
        ),
    ]
