# Generated by Django 5.1.5 on 2026-08-25 16:05

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def close_duplicate_pending_payments(apps, schema_editor):
    PaymentTransaction = apps.get_model("finance", "PaymentTransaction")
    seen = set()
    pending = PaymentTransaction.objects.filter(status="pending").order_by(
        "project_id", "user_id", "-requested_at"
    )
    for payment in pending.iterator():
        key = (payment.project_id, payment.user_id)
        if key in seen:
            payment.status = "expired"
            payment.completed_at = timezone.now()
            payment.raw_response_redacted = {"reason": "duplicate_pending_closed_by_migration"}
            payment.save(
                update_fields=("status", "completed_at", "raw_response_redacted")
            )
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0003_projectstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(close_duplicate_pending_payments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('project', 'user'), name='one_pending_payment_per_user_project'),
        ),
    ]
