# Generated by Django 5.1.5 on 2026-08-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymenttransaction_one_pending_payment_per_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=16),
        ),
    ]
