# Generated by Django 5.1.5 on 2026-09-04 18:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_paymenttransaction_status'),
        ('organizations', '0002_alter_organization_status'),
        ('planning', '0002_alter_projectstage_image'),
        ('projects', '0010_onboarding_conflict_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('purpose', models.CharField(max_length=500)),
                ('beneficiary', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('evidence', 'En preuve'), ('review', 'En revue'), ('verified', 'Vérifiée'), ('authorized', 'Autorisée'), ('rejected', 'Refusée'), ('closed', 'Close')], default='draft', max_length=16)),
                ('status_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_expense_requests', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='planning.projectstage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpenseRequestTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('evidence', 'En preuve'), ('review', 'En revue'), ('verified', 'Vérifiée'), ('authorized', 'Autorisée'), ('rejected', 'Refusée'), ('closed', 'Close')], max_length=16)),
                ('new_status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('evidence', 'En preuve'), ('review', 'En revue'), ('verified', 'Vérifiée'), ('authorized', 'Autorisée'), ('rejected', 'Refusée'), ('closed', 'Close')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_request_transitions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='finance.expenserequest')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['organization', 'project', 'status'], name='finance_exp_organiz_7b3de9_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenserequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_request_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expenserequesttransition',
            constraint=models.UniqueConstraint(fields=('request', 'status_version'), name='unique_expense_status_version'),
        ),
    ]
