# Generated by Django 5.1.5 on 2026-09-04 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0008_evidencerecord_preview_file_and_more'),
        ('finance', '0004_expenserequest_expenserequesttransition_and_more'),
        ('organizations', '0002_alter_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='expense_type',
            field=models.CharField(choices=[('material', 'Matériaux'), ('labor', 'Main-d’œuvre'), ('service', 'Prestation'), ('equipment', 'Équipement'), ('other', 'Autre')], default='other', max_length=16),
        ),
        migrations.CreateModel(
            name='ExpenseRequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('quote', 'Devis'), ('delivery_note', 'Bon de livraison'), ('field_evidence', 'Preuve terrain')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('rejected', 'Rejetée'), ('replaced', 'Remplacée')], default='active', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_expense_attachments', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_attachments', to='collaboration.evidencerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_attachments', to='organizations.organization')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='finance.expenserequestattachment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='finance.expenserequest')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['request', 'document_type', 'status'], name='finance_exp_request_db964e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('request', 'evidence'), name='unique_active_expense_evidence')],
            },
        ),
    ]
