# Generated by Django 5.1.5 on 2026-09-04 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expenserequest_expense_type_expenserequestattachment'),
        ('organizations', '0002_alter_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequestattachment',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Facture'), ('quote', 'Devis'), ('delivery_note', 'Bon de livraison'), ('field_evidence', 'Preuve terrain'), ('work_evidence', 'Travaux réalisés'), ('progress_evidence', 'Progression du chantier')], max_length=24),
        ),
        migrations.CreateModel(
            name='ExpenseTechnicalOpinion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approuvé'), ('conditional', 'Conditionnel'), ('rejected', 'Rejeté')], max_length=16)),
                ('reason', models.CharField(max_length=1000)),
                ('reviewed_status_version', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_technical_opinions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_technical_opinions', to='organizations.organization')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_opinions', to='finance.expenserequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('request',), name='one_current_expense_technical_opinion'), models.UniqueConstraint(fields=('request', 'reviewed_status_version'), name='unique_expense_opinion_reviewed_version')],
            },
        ),
    ]
