# Generated by Django 5.1.5 on 2026-09-04 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expenserequestattachment_document_type_and_more'),
        ('organizations', '0002_alter_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='pivot_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='risk_level',
            field=models.CharField(default='low', max_length=12),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='risk_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExpensePivotVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approuvée'), ('rejected', 'Rejetée')], max_length=16)),
                ('reason', models.CharField(max_length=1000)),
                ('reviewed_status_version', models.PositiveIntegerField()),
                ('risk_score_snapshot', models.PositiveSmallIntegerField()),
                ('risk_reasons_snapshot', models.JSONField(default=list)),
                ('is_exceptional', models.BooleanField(default=False)),
                ('confirmation', models.CharField(blank=True, max_length=100)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_pivot_verifications', to='organizations.organization')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pivot_verifications', to='finance.expenserequest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_pivot_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('request',), name='one_current_expense_pivot_verification'), models.UniqueConstraint(fields=('request', 'reviewed_status_version'), name='unique_pivot_verification_request_version')],
            },
        ),
    ]
