# Generated by Django 5.1.5 on 2026-09-07 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expenserequest_pivot_review_required_and_more'),
        ('organizations', '0002_alter_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseOwnerDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Autorisée'), ('rejected', 'Refusée')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('decided_status_version', models.PositiveIntegerField()),
                ('resulting_status_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_owner_decisions', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_owner_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_decisions', to='finance.expenserequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('request', 'decided_status_version'), name='unique_owner_decision_request_version')],
            },
        ),
    ]
