# Generated by Django 5.1.5 on 2026-09-07 11:33

import apps.finance.models
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_pivot_references(apps, schema_editor):
    PaymentTransaction = apps.get_model("finance", "PaymentTransaction")
    for transaction in PaymentTransaction.objects.all().iterator():
        transaction.pivot_reference = f"PIVOT-{uuid.uuid4()}"
        transaction.save(update_fields=("pivot_reference",))


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_expenseownerdecision'),
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0010_onboarding_conflict_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='beneficiary_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='expense_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='finance.expenserequest'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='operator_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='owner_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='finance.expenseownerdecision'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pivot_reference',
            field=models.CharField(default=apps.finance.models.payment_reference, editable=False, max_length=100),
        ),
        migrations.RunPython(backfill_pivot_references, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('expense_request__isnull', False), ('status', 'pending')), fields=('expense_request',), name='one_pending_payment_per_expense_request'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('expense_request__isnull', False), ('status', 'success')), fields=('expense_request',), name='one_success_payment_per_expense_request'),
        ),
    ]
