# Generated by Django 5.1.5 on 2026-09-07 11:34

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_paymenttransaction_beneficiary_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='pivot_reference',
            field=models.CharField(default=apps.finance.models.payment_reference, editable=False, max_length=100, unique=True),
        ),
    ]
