# Generated by Django 5.1.5 on 2026-08-20 14:13

from django.db import migrations, models

import apps.collaboration.models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdocument",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=apps.collaboration.models.collaboration_path
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to=apps.collaboration.models.collaboration_path
            ),
        ),
    ]
