# Generated by Django 5.1.5 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_alter_projectdocument_file_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=16),
        ),
    ]
