# Generated by Django 5.1.5 on 2026-09-04 15:47

import apps.collaboration.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def register_existing_files(apps, schema_editor):
    Evidence = apps.get_model('collaboration', 'EvidenceRecord')
    Document = apps.get_model('collaboration', 'ProjectDocument')
    Image = apps.get_model('collaboration', 'ProjectImage')
    status_map = {'pending': 'submitted', 'verified': 'verified', 'approved': 'approved', 'rejected': 'rejected'}
    for document in Document.objects.iterator():
        title = document.title.lower()
        evidence_type = 'document'
        for token, value in (
            ('facture', 'invoice'), ('devis', 'quote'), ('livraison', 'delivery_note'),
            ('inspection', 'inspection'), ('compte rendu', 'minutes'), ('procès-verbal', 'minutes'),
        ):
            if token in title:
                evidence_type = value
                break
        Evidence.objects.create(
            evidence_key=uuid.uuid4(), organization_id=document.organization_id,
            project_id=document.project_id, author_id=document.uploaded_by_id,
            document_id=document.pk, evidence_type=evidence_type, title=document.title,
            status=status_map.get(document.status, 'submitted'), version=1,
            source_metadata={'legacy_model': 'ProjectDocument', 'backfilled': True},
        )
    for image in Image.objects.iterator():
        Evidence.objects.create(
            evidence_key=uuid.uuid4(), organization_id=image.organization_id,
            project_id=image.project_id, author_id=image.uploaded_by_id,
            image_id=image.pk, evidence_type='photo',
            title=image.caption or 'Photo du chantier', status='submitted', version=1,
            source_metadata={'legacy_model': 'ProjectImage', 'backfilled': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0003_alter_projectdocument_status'),
        ('organizations', '0002_alter_organization_status'),
        ('planning', '0002_alter_projectstage_image'),
        ('projects', '0010_onboarding_conflict_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('invoice', 'Facture'), ('quote', 'Devis'), ('delivery_note', 'Bon de livraison'), ('minutes', 'Compte rendu'), ('inspection', 'Inspection'), ('document', 'Autre document')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('status', models.CharField(choices=[('submitted', 'Déposée'), ('verified', 'Vérifiée'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='submitted', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_file', models.FileField(blank=True, max_length=255, upload_to=apps.collaboration.models.collaboration_path)),
                ('request_type', models.CharField(blank=True, max_length=80)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_evidence', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_record', to='collaboration.projectdocument')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_record', to='collaboration.projectimage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='organizations.organization')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='collaboration.evidencerecord')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='projects.project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_records', to='planning.projectstage')),
            ],
            options={
                'ordering': ('-captured_at',),
                'indexes': [models.Index(fields=['organization', 'project', 'evidence_type'], name='collaborati_organiz_e393e6_idx'), models.Index(fields=['project', 'status', '-captured_at'], name='collaborati_project_28ebf5_idx')],
                'constraints': [models.UniqueConstraint(fields=('evidence_key', 'version'), name='unique_evidence_version'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='evidence_version_positive'), models.CheckConstraint(condition=models.Q(('document__isnull', False), ('image__isnull', False), _negated=True), name='evidence_single_legacy_source')],
            },
        ),
        migrations.RunPython(register_existing_files, migrations.RunPython.noop),
    ]
