# Generated by Django 5.1.5 on 2026-09-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0004_evidence_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencerecord',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_record', to='collaboration.projectdocument'),
        ),
        migrations.AlterField(
            model_name='evidencerecord',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_record', to='collaboration.projectimage'),
        ),
    ]
