# Generated by Django 5.1.5 on 2026-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0005_preserve_evidence_on_source_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='location_accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='location_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='location_status',
            field=models.CharField(choices=[('not_requested', 'Non demandée'), ('granted', 'Autorisée'), ('denied', 'Refusée'), ('unavailable', 'Indisponible')], default='not_requested', max_length=16),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
