# Generated by Django 5.1.5 on 2026-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0006_evidencerecord_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='correction_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='is_administrative_correction',
            field=models.BooleanField(default=False),
        ),
    ]
