# Generated by Django 5.1.5 on 2026-09-04 17:28

import apps.collaboration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0007_evidencerecord_correction_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='preview_file',
            field=models.ImageField(blank=True, max_length=255, upload_to=apps.collaboration.models.collaboration_path),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='submission_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
