# Generated by Django 5.1.5 on 2026-08-28 12:06

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
                ('monthly_price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix mensuel')),
                ('yearly_price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix annuel')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='devise')),
                ('max_active_projects', models.PositiveIntegerField(blank=True, null=True, verbose_name='projets actifs maximum')),
                ('max_internal_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='membres internes maximum')),
                ('storage_limit_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='stockage maximum (Mo)')),
                ('advanced_reports_enabled', models.BooleanField(default=False, verbose_name='rapports avancés')),
                ('ai_assistant_enabled', models.BooleanField(default=False, verbose_name='assistant IA')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='fonctionnalités')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_public', models.BooleanField(default=True, verbose_name='visible dans le pricing')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre d’affichage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'forfait',
                'verbose_name_plural': 'forfaits',
                'ordering': ('display_order', 'monthly_price', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_price__gte', 0)), name='subscription_plan_monthly_price_non_negative'), models.CheckConstraint(condition=models.Q(('yearly_price__gte', 0)), name='subscription_plan_yearly_price_non_negative'), models.CheckConstraint(condition=models.Q(('max_active_projects__isnull', True), ('max_active_projects__gt', 0), _connector='OR'), name='subscription_plan_project_limit_positive'), models.CheckConstraint(condition=models.Q(('max_internal_members__isnull', True), ('max_internal_members__gt', 0), _connector='OR'), name='subscription_plan_member_limit_positive'), models.CheckConstraint(condition=models.Q(('storage_limit_mb__isnull', True), ('storage_limit_mb__gt', 0), _connector='OR'), name='subscription_plan_storage_limit_positive')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('grace', 'Période de grâce'), ('read_only', 'Lecture seule'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='trial', max_length=16, verbose_name='statut')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=10, verbose_name='périodicité')),
                ('trial_started_at', models.DateTimeField(blank=True, null=True, verbose_name='début de l’essai')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fin de l’essai')),
                ('current_period_started_at', models.DateTimeField(blank=True, null=True, verbose_name='début de la période')),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fin de la période')),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fin de la grâce')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('plan_snapshot', models.JSONField(blank=True, default=dict, verbose_name='instantané du forfait')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='organizations.organization', verbose_name='organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='forfait')),
            ],
            options={
                'verbose_name': 'abonnement d’organisation',
                'verbose_name_plural': 'abonnements d’organisation',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80, verbose_name='type d’événement')),
                ('previous_status', models.CharField(blank=True, choices=[('trial', 'Essai'), ('active', 'Actif'), ('grace', 'Période de grâce'), ('read_only', 'Lecture seule'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], max_length=16, verbose_name='ancien statut')),
                ('new_status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('grace', 'Période de grâce'), ('read_only', 'Lecture seule'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], max_length=16, verbose_name='nouveau statut')),
                ('plan_snapshot', models.JSONField(default=dict, verbose_name='instantané du forfait')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='survenu le')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_events', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='subscriptions.organizationsubscription', verbose_name='abonnement')),
            ],
            options={
                'verbose_name': 'événement d’abonnement',
                'verbose_name_plural': 'événements d’abonnement',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['subscription', '-occurred_at'], name='subscriptio_subscri_c1e3d6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status', 'current_period_ends_at'], name='subscriptio_status_339e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status', 'trial_ends_at'], name='subscriptio_status_c3a11a_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('trial_started_at__isnull', True), ('trial_ends_at__isnull', True), ('trial_ends_at__gt', models.F('trial_started_at')), _connector='OR'), name='subscription_trial_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_started_at__isnull', True), ('current_period_ends_at__isnull', True), ('current_period_ends_at__gt', models.F('current_period_started_at')), _connector='OR'), name='subscription_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('grace_ends_at__isnull', True), ('current_period_ends_at__isnull', True), ('grace_ends_at__gte', models.F('current_period_ends_at')), _connector='OR'), name='subscription_grace_after_period_end'),
        ),
    ]
