# Generated by Django 5.1.5 on 2026-08-28 12:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('subscriptions', '0003_backfill_active_organization_trials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('operator', models.CharField(max_length=30)),
                ('payer_phone', models.CharField(max_length=20)),
                ('provider', models.CharField(default='mesomb', max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('pending', 'En attente'), ('success', 'Réussi'), ('refused', 'Refusé'), ('cancelled', 'Annulé'), ('failed', 'Échoué'), ('expired', 'Expiré')], default='initiated', max_length=16)),
                ('plan_snapshot', models.JSONField(default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.organizationsubscription')),
            ],
            options={
                'ordering': ('-requested_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('initiated', 'pending'))), fields=('organization',), name='one_uncertain_subscription_payment_per_org')],
            },
        ),
    ]
