# Generated by Django 5.1.5 on 2026-08-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='pending_billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='pending_effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='pending_period_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='action',
            field=models.CharField(choices=[('renewal', 'Renouvellement'), ('upgrade', 'Montée de gamme'), ('downgrade', 'Baisse programmée')], default='renewal', max_length=16),
        ),
    ]
