# Generated by Django 5.1.5 on 2026-08-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_organizationsubscription_pending_billing_cycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionNoticeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=40)),
                ('channel', models.CharField(choices=[('in_app', 'Dans l’application'), ('email', 'E-mail')], max_length=10)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_deliveries', to='subscriptions.organizationsubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'recipient', 'milestone', 'channel'), name='unique_subscription_notice_delivery')],
            },
        ),
    ]
