# Generated by Django 5.1.5 on 2026-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionnoticedelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='receipt_reference',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
