# Generated by Django 5.1.5 on 2026-09-07 19:33

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


def trace_existing_stock(apps, schema_editor):
    StockItem = apps.get_model("inventory", "StockItem")
    StockMovement = apps.get_model("inventory", "StockMovement")
    for item in StockItem.objects.all().iterator():
        movements = list(StockMovement.objects.filter(item_id=item.pk))
        for movement in movements:
            movement.source_quantity = movement.variation
            movement.normalized_quantity = abs(movement.variation)
            movement.source_unit = item.unit
            movement.source_reference = "Correction historique"
            movement.save(update_fields=(
                "source_quantity", "normalized_quantity", "source_unit", "source_reference",
            ))
        traced_total = sum((movement.variation for movement in movements), Decimal("0"))
        opening = item.quantity - traced_total
        if opening:
            StockMovement.objects.create(
                organization_id=item.organization_id, project_id=item.project_id,
                item_id=item.pk, movement_type="correction",
                source_reference="Stock d'ouverture migré", source_quantity=opening,
                source_unit=item.unit, conversion_factor=1,
                normalized_quantity=abs(opening), variation=opening,
                resulting_quantity=opening, reason="Reprise du solde antérieur à E21-S1",
                actor_id=item.created_by_id, idempotency_key=uuid.uuid4(),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=16, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='facteur de conversion'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchased', 'Acheté'), ('delivered', 'Livré'), ('consumed', 'Consommé'), ('correction', 'Correction inventaire')], default='correction', max_length=16),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='normalized_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='quantité convertie'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='quantité source'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_reference',
            field=models.CharField(default="Stock d'ouverture", max_length=200, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_unit',
            field=models.CharField(default='unité', max_length=30, verbose_name='unité source'),
        ),
        migrations.RunPython(trace_existing_stock, migrations.RunPython.noop),
    ]
