# Generated by Django 5.1.5 on 2026-09-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0008_evidencerecord_preview_file_and_more'),
        ('inventory', '0002_stockmovement_conversion_factor_and_more'),
        ('planning', '0009_stageverificationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='collaboration.evidencerecord'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='planning.projectstage'),
        ),
    ]
