# Generated by Django 5.1.5 on 2026-09-07 20:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_evidence_stockmovement_stage'),
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0010_onboarding_conflict_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryExpectedRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=200, verbose_name='ouvrage')),
                ('unit', models.CharField(max_length=30, verbose_name='unité')),
                ('minimum_quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('assumptions', models.TextField(max_length=3000, verbose_name='hypothèses')),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_expected_ranges', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_expected_ranges', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_expected_ranges', to='projects.project')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newer_versions', to='inventory.inventoryexpectedrange')),
            ],
            options={
                'ordering': ('work_type', '-version'),
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='expected_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.inventoryexpectedrange'),
        ),
        migrations.AddConstraint(
            model_name='inventoryexpectedrange',
            constraint=models.UniqueConstraint(fields=('project', 'work_type', 'unit', 'version'), name='unique_inventory_expected_range_version'),
        ),
    ]
