# Generated by Django 5.1.5 on 2026-09-08 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_paymenttransaction_pivot_reference'),
        ('inventory', '0004_inventoryexpectedrange_stockitem_expected_range_and_more'),
        ('organizations', '0002_alter_organization_status'),
        ('projects', '0010_onboarding_conflict_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryexpectedrange',
            name='out_of_range_action',
            field=models.CharField(choices=[('flag', 'Signaler sans bloquer'), ('block', 'Bloquer avant paiement')], default='flag', max_length=10),
        ),
        migrations.CreateModel(
            name='InventoryAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_range_version', models.PositiveIntegerField()),
                ('minimum_snapshot', models.DecimalField(decimal_places=4, max_digits=16)),
                ('maximum_snapshot', models.DecimalField(decimal_places=4, max_digits=16)),
                ('observed_quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit_snapshot', models.CharField(max_length=30)),
                ('direction', models.CharField(choices=[('below', 'Sous la plage'), ('above', 'Au-dessus de la plage')], max_length=10)),
                ('action', models.CharField(choices=[('flag', 'Signaler sans bloquer'), ('block', 'Bloquer avant paiement')], max_length=10)),
                ('movement_ids', models.JSONField(default=list)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('resolved', 'Résolue')], default='open', max_length=12)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('expected_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='inventory.inventoryexpectedrange')),
                ('expense_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_anomalies', to='finance.expenserequest')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='inventory.stockitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_anomalies', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_anomalies', to='projects.project')),
            ],
            options={
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['project', 'status', '-detected_at'], name='inventory_i_project_95f180_idx')],
            },
        ),
    ]
