# Generated by Django 5.1.5 on 2026-09-08 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0008_evidencerecord_preview_file_and_more'),
        ('inventory', '0005_inventoryexpectedrange_out_of_range_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAnomalyResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=12)),
                ('decision_reason', models.TextField(blank=True, max_length=3000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='inventory.inventoryanomaly')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_inventory_anomaly_resolutions', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ManyToManyField(related_name='inventory_anomaly_resolutions', to='collaboration.evidencerecord')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_inventory_anomaly_resolutions', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_inventory_anomaly_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('submitted_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('anomaly',), name='one_pending_inventory_anomaly_resolution')],
            },
        ),
    ]
