# Generated by Django 5.1.5 on 2026-08-20 13:46

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.planning.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0003_projectstatushistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, verbose_name="description"),
                ),
                ("start_date", models.DateField(verbose_name="date de début")),
                ("end_date", models.DateField(verbose_name="date de fin")),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="coût estimé",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="coût réel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("active", "Active"),
                            ("complete", "Terminée"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="statut",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.planning.models.stage_image_path,
                        verbose_name="image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_project_stages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_stages",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ("start_date", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["organization", "project", "status"],
                        name="planning_pr_organiz_850ef6_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="stage_end_not_before_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estimated_cost__gte", 0)),
                        name="stage_estimated_cost_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("actual_cost__gte", 0)),
                        name="stage_actual_cost_non_negative",
                    ),
                ],
            },
        ),
    ]
