# Generated by Django 5.1.5 on 2026-08-20 13:54

import django.core.validators
from django.db import migrations, models

import apps.planning.models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectstage",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=apps.planning.models.stage_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(("jpg", "jpeg", "png", "webp")),
                    apps.planning.models.validate_stage_image_size,
                ],
                verbose_name="image",
            ),
        ),
    ]
