# Generated by Django 5.1.5 on 2026-09-07 12:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0008_evidencerecord_preview_file_and_more'),
        ('organizations', '0002_alter_organization_status'),
        ('planning', '0002_alter_projectstage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageProgressDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_progress_declarations', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaboration.evidencerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_declarations', to='planning.projectstage')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageProgressVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_progress_verifications', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaboration.evidencerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_verifications', to='planning.projectstage')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
