# Generated by Django 5.1.5 on 2026-09-07 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('planning', '0003_stageprogressdeclaration_stageprogressverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTechnicalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approuvée'), ('conditional', 'Approuvée sous conditions'), ('rejected', 'Rejetée')], max_length=16)),
                ('reason', models.CharField(max_length=1000)),
                ('corrective_actions', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='technical_review', to='planning.stageprogressdeclaration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_technical_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
