# Generated by Django 5.1.5 on 2026-09-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_stagedigitalverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageprogressverification',
            name='declaration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_verification', to='planning.stageprogressdeclaration'),
        ),
        migrations.AddField(
            model_name='stageprogressverification',
            name='digital_verification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_verification', to='planning.stagedigitalverification'),
        ),
        migrations.AddField(
            model_name='stageprogressverification',
            name='logical_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='stageprogressverification',
            name='quantities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stageprogressverification',
            name='reservations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stageprogressverification',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
