# Generated by Django 5.1.5 on 2026-09-07 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0008_evidencerecord_preview_file_and_more'),
        ('organizations', '0002_alter_organization_status'),
        ('planning', '0006_stageprogressverification_declaration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageSiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField()),
                ('location_label', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_site_visits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_visits', to='planning.projectstage')),
            ],
            options={
                'ordering': ('-visited_at',),
            },
        ),
        migrations.CreateModel(
            name='StageSiteVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checklist', models.JSONField(default=list)),
                ('reservations', models.JSONField(blank=True, default=list)),
                ('result', models.CharField(choices=[('passed', 'PIVOT Site Verified'), ('conditional', 'Conforme sous réserves'), ('failed', 'Non conforme')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ManyToManyField(related_name='site_verifications', to='collaboration.evidencerecord')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_site_verifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('technical_verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_verifications', to='planning.stageprogressverification')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='planning.stagesitevisit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
