# Generated by Django 5.1.5 on 2026-09-07 13:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('planning', '0007_stagesitevisit_stagesiteverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='stage_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('foundation', 'Fondations'), ('structure', 'Structure'), ('finishing', 'Finitions'), ('safety', 'Sécurité')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='StageInspectionRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_required', models.BooleanField()),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('technical_verification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment', to='planning.stageprogressverification')),
            ],
        ),
        migrations.CreateModel(
            name='StageInspectionRiskOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=2000)),
                ('confirmation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_risk_overrides', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='override', to='planning.stageinspectionriskassessment')),
            ],
        ),
        migrations.CreateModel(
            name='StageInspectionRiskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('stage_types', models.JSONField(blank=True, default=list)),
                ('minimum_stage_value', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('maximum_progress_variance', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
                ('failed_history_threshold', models.PositiveSmallIntegerField(default=1)),
                ('require_on_anomaly', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspection_risk_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_risk_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='stageinspectionriskassessment',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='planning.stageinspectionriskrule'),
        ),
        migrations.AddConstraint(
            model_name='stageinspectionriskrule',
            constraint=models.UniqueConstraint(fields=('organization', 'version'), name='unique_inspection_risk_rule_version'),
        ),
    ]
