# Generated by Django 5.1.5 on 2026-09-07 14:01

import apps.planning.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_status'),
        ('planning', '0008_projectstage_stage_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageVerificationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default=apps.planning.models.verification_report_reference, editable=False, max_length=40, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_stage_verification_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('technical_verification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='planning.stageprogressverification')),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
    ]
