# Generated by Django 5.1.5 on 2026-08-14 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="action")),
                ("target_type", models.CharField(max_length=100, verbose_name="type de cible")),
                (
                    "target_id",
                    models.CharField(max_length=100, verbose_name="identifiant de cible"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="métadonnées"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acteur",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="organizations.organization",
                        verbose_name="organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "événement d'audit",
                "verbose_name_plural": "événements d'audit",
                "ordering": ("-created_at",),
            },
        ),
    ]
