# Generated by Django 5.1.5 on 2026-09-04 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_platformconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='evidence_download_requires_approval',
            field=models.BooleanField(default=True, verbose_name='téléchargement des preuves après approbation uniquement'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='evidence_location_restricted',
            field=models.BooleanField(default=True, verbose_name='coordonnées réservées au propriétaire et aux contrôleurs'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='evidence_retention_days',
            field=models.PositiveSmallIntegerField(default=1825, validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(3650)], verbose_name='rétention minimale des preuves (jours)'),
        ),
    ]
