# Generated by Django 5.1.5 on 2026-09-08 16:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_platformconfiguration_evidence_download_requires_approval_and_more'),
        ('organizations', '0002_alter_organization_status'),
        ('subscriptions', '0007_subscriptionpayment_receipt_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotPricingHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=120)),
                ('proposed_monthly_price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('positive_responses', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('testing', 'En test'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='testing', max_length=16)),
                ('assumptions', models.TextField(max_length=3000)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_pricing_hypotheses', to='subscriptions.subscriptionplan')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_pricing_hypotheses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PilotRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_role', models.CharField(choices=[('client', 'Client'), ('contractor', 'Entrepreneur')], max_length=16)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_recommendations', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_pilot_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
    ]
