# Generated by Django 5.1.5 on 2026-09-08 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_pilotpricinghypothesis_pilotrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_days', models.PositiveSmallIntegerField(choices=[(30, '30 jours'), (60, '60 jours'), (90, '90 jours')])),
                ('as_of_date', models.DateField()),
                ('decision', models.CharField(choices=[('go', 'Go'), ('conditional_go', 'Go conditionnel'), ('no_go', 'No-go')], max_length=20)),
                ('rationale', models.TextField(max_length=3000)),
                ('product_decisions', models.TextField(max_length=5000)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_pilot_review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-as_of_date', '-recorded_at'),
                'constraints': [models.UniqueConstraint(fields=('horizon_days', 'as_of_date'), name='unique_pilot_review_horizon_date')],
            },
        ),
    ]
