# Generated by Django 5.1.5 on 2026-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="nom")),
                ("slug", models.SlugField(max_length=180, unique=True, verbose_name="identifiant")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspendue")],
                        default="active",
                        max_length=16,
                        verbose_name="statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
            ],
            options={
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
                "ordering": ("name",),
            },
        ),
    ]
